config/routes.rb
Rails.application.routes.draw do
  root "home#show"

  resource :session
  resources :videos

  get "/auth/:provider/callback", :to => "sessions#create"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.authenticated?
    return unless user.admin?

    can :manage, :all
  end
end

app/models/guest_user.rb
class GuestUser
  def authenticated?
    false
  end
end

app/models/presenter.rb
class Presenter < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum :role => %i(viewer admin)

  def authenticated?
    true
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :presenter
  mount_uploader :thumbnail, ThumbnailUploader

  enum :host   => %i(you_tube vimeo)
  enum :status => %i(pending published)

  def self.latest
    published.order(:created_at => :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Trailblazer::Operation::Controller

  protect_from_forgery :with => :exception
  helper_method :current_user

  rescue_from CanCan::AccessDenied do
    redirect_to root_url,
      :alert => "Access denied. You do not have permission to do that."
  end

  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(:id => session[:user_id])
    end

    @current_user || GuestUser.new
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @latest_videos = Video.latest
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    run Authentication::LoginWithOmniAuth do |op|
      login(op.user)
      return redirect_to root_path, :notice => "Successfully logged in!"
    end
  end

  def destroy
    logout
    redirect_to root_path, :notice => "Successfully logged out!"
  end

  private

  def process_params!(params)
    params.merge!(
      :auth => env["omniauth.auth"]
    )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    form Video::Create
  end

  def create
    run Video::Create do
      return redirect_to root_path, :notice => "Successfully added video!"
    end

    render :new
  end

  def process_params!(params)
    params.merge!(
      :current_user => current_user
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def presenters
    Presenter.order(:name).map { |p| [p.name, p.id] }
  end

  def hosts
    Video.hosts.keys.map { |key| [key.titleize, key] }
  end

  def video_statuses
    Video.statuses.keys.map { |key| [key.titleize, key] }
  end

  def smooth_link_to(text, anchor)
    href = root_path(:anchor => anchor)
    href = "##{anchor}" if controller_name == "home"

    link_to text, href, :class => "scroll-smooth"
  end
end

app/views/application/_flash.html.slim
- if flash[:notice].present?
  .flash.alert.alert-success role="alert"
    .container= flash[:notice]

- if flash[:alert].present?
  .flash.alert.alert-danger role="alert"
    .container= flash[:alert]

app/views/home/show.html.slim
#home
  .bg-intro
    .container.container-intro
      .row-intro.row
        .col-sm-5.col-xs-12
          h1.title-intro.animated.fadeInDown Ruby Videos
          h2.subtitle-intro.animated.fadeInLeft A curated listing of quality videos about or related to the Ruby programming language.
          .btn-delay.animated.fadeInUp
            a.btn.btn-white.scroll-smooth href="#features" Suggest a Video
        .col-browser.col-sm-7.col-xs-12
          .col-sl.animated.fadeInDown
            = image_tag "browser-slider/browser.png", :class => "img-browser"
            .wrapper-sl.wrapper-browser
              ul#slider-intro.slider
                li= image_tag "browser-slider/652x340.gif"
                li= image_tag "browser-slider/652x340.gif"
              .wrapper-nav
                .div-p.div-p-browser
                  i#p-intro
                .div-n.div-n-browser
                  i#n-intro
#latest
  .bg-portfolio
    .container
      .row
        .col-sm-12
          h1.header-title LATEST VIDEOS
          h2.subtitle Check out the latest videos added to the collection
          hr.hr-portfolio
      .row
        ul.ul-portfolio
          li.filter.wow.fadeInLeft data-filter="all"
            | ALL
          li.filter.wow.fadeInUp data-filter="women" data-wow-delay="0.2s"
            | TESTING
          li.filter.wow.fadeInDown data-filter="perf" data-wow-delay="0.3s"
            | PERFORMANCE
          li.filter.wow.fadeInRight data-filter="web-design"
            | SECURITY
      #Grid.row
        = concept("video/cell", collection: @latest_videos)

        .mix.women.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="women" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.web-design.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="design" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.perf.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.perf href="images/portfolio/1280x800.gif" title="This is a video title"
                span.glyphicon.glyphicon-play
        .mix.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.web-design.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="design" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.web-design.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="gallery-1" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.women.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="women" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.women.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="women" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
        .mix.web-design.all.col-sm-4
          .img-wrapper
            = image_tag "portfolio/400x300.gif", :class => "img-portfolio"
            .bg-img-portfolio
            .lightbox-wrapper
              a.nivoz data-lightbox-gallery="design" href="images/portfolio/1280x800.gif" title="This is an image title"
                span.glyphicon.glyphicon-play
.bg-quote
  .container
    .row-quote.row
      .col-md-12.wow.fadeInUp
        h5
          i.fa.fa-quote-left
          | Ruby Videos is a great way for Ruby developers to keep up to date with the latest quality videos.
          i.fa.fa-quote-right
#featuring
  .bg-team
    .container
      .row
        .col-sm-12.wow.fadeInUp data-wow-delay="0.2s"
          h1.header-title FEATURING
          h2.subtitle Including videos from these presenters
          hr
      .row.row-team
        .col-team.col-sm-4.wow.pulse
          .wrapper-team-pic
            = image_tag "team/team-1.jpg", :class => "img-team"
            .team-hover-bg
            a href="#"
              i.fa.fa-twitter.team-icon.team-t
            a href="#"
              i.fa.fa-github.team-icon.team-d
          h2.team-title Andy Pike
          h3.team-subtitle Technical Director
#contact
  .bg-contact.grey
    .container-contact.container
      .row
        .col-sm-12
          h1.header-title.wow.fadeInLeft CONTACT US
          h2.subtitle.wow.fadeInRight Feel free to contact us anytime!
          hr.hr-contact
      .row-contact.row
        .col-sm-12
          .row.wow.fadeInUp
            form#ajax_form.form-contact action="email.php" method="POST" role="form"
              .col-sm-12
                .form-group
                  input#name.form-control.form-flat name="name" placeholder="Name" type="text"
              .col-sm-12
                .form-group
                  input#email.form-control.form-flat name="email" placeholder="Email" type="text"
              .col-sm-12
                .form-group
                  textarea#message.form-control.form-flat name="message"
                button.submit.btn.btn-flat type="submit" Submit
.bg-subscribe
  .container-subscribe.container
    .row-subscribe.row
      .col-subscribe.col-sm-8.col-sm-offset-2.wow.fadeInRight
        input.form-control.form-flat.subscribe-mail.hidden-xs placeholder="Add your email address" type="email"
        input.form-control.form-flat.subscribe-mail.visible-xs type="email"
        a.btn.btn-flat href="#" SUBSCRIBE

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="A curated listing of quality videos about or related to the Ruby programming language." name="description"
    meta content="Andy Pike" name="author"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title Ruby Videos | A curated listing of quality videos about or related to the Ruby programming language.

    = stylesheet_link_tag    "application"
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700,300,800"
    = javascript_include_tag "application"
    = csrf_meta_tags

    /![if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

  body data-offset="50" data-spy="scroll" data-target=".scroll-bootstrap"
    nav.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          = link_to root_path do
            = image_tag "logo.png", :class => "navbar-brand"

          - if current_user.authenticated?
            .logged_in.pull-left Logged in as #{current_user.nickname}

          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .scroll-bootstrap.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            li= smooth_link_to "Home", "home"
            li= smooth_link_to "Latest", "latest"
            li= smooth_link_to "Featuring", "featuring"
            li= smooth_link_to "Contact", "contact"

            - if can? :manage, Video
              li= link_to "Add Video", new_video_path

            - if current_user.authenticated?
              li= link_to "Logout", session_path, :method => :delete
            - else
              li= link_to "Login with GitHub", "/auth/github"

    = render "flash"
    = yield

    .bg-footer
      .container
        .row.row-footer
          .col-md-12
            .wrapper-social
              a href="http://twitter.com/rubyvideos_" target="_blank"
                i.fa.fa-twitter.twitter-footer.wow.bounce data-wow-delay="0.2s"
              a href="https://github.com/andypike/ruby_videos" target="_blank"
                i.fa.fa-github.github-footer.wow.bounce data-wow-delay="0.2s"
    .bg-footer-bottom
      .container
        .row-footer-bottom.row
          .col-sm-12
            p.pull-left
              | Made with
              i.fa.fa-heart
              | by #{link_to "Andy Pike", "http://twitter.com/andypike"} 2015.

    javascript:
      wow = new WOW(
        {
          animateClass: 'animated',
          mobile: false
        }
      );
      wow.init();

app/views/videos/new.html.slim
.page#add-video
  .container.container-intro
    .row
      .col-md-12
        h1 Add Video

        = simple_form_for @form do |f|
          = f.input :title
          = f.input :presenter_id, :collection => presenters
          = f.input :originally_posted_on, :label => "Original date"
          = f.input :original_url
          = f.input :host, :collection => hosts
          = f.input :embed_url
          = f.input :status, :collection => video_statuses
          = f.input :thumbnail
          = f.submit "Save"